name: gmt-examples
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12
  - gmt=6.5.0
  - myst-parser
  - sphinx
  - sphinx-design
  - sphinx_gmt
  - sphinx_rtd_theme
  - sphinxcontrib-youtube
