#
# Build documentation and deploy
#
name: Docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/**'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Get current week number of year
        id: date
        run: echo "date=$(date +%Y-W%W)" >> $GITHUB_OUTPUT  # e.g., 2024-W19

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v1.9.0
        with:
          environment-file: environment.yml
          cache-downloads: false
          cache-environment: true
          # environment cache is persistent for one week.
          cache-environment-key: micromamba-environment-${{ steps.date.outputs.date }}

      - name: Build the website
        run: make -C docs clean html

      - name: Deploy to gh-pages
        if: success() && github.event_name == 'push'
        # Don't use tags: https://julienrenaux.fr/2019/12/20/github-actions-security-risk/
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html/
          # Only keep the latest commit to avoid bloating the repository
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
